// web/src/views/RequirementDetail.vue
<template>
  <div class="page-pad detail-page" v-if="item">
    <a-breadcrumb><a-breadcrumb-item><a @click="$router.push('/requirements')">需求</a></a-breadcrumb-item><a-breadcrumb-item>{{ item.code }}</a-breadcrumb-item></a-breadcrumb>
    <div class="detail-header"><div><div class="mono text-secondary">{{ item.code }}</div><h2>{{ item.title }}</h2><p>{{ item.description || '暂无描述' }}</p></div><a-space><a-button :disabled="!app.canWrite" @click="startEdit"><template #icon><EditOutlined /></template>编辑</a-button><a-button :loading="exporting" :disabled="!app.canWrite" @click="exportPackage"><template #icon><ExportOutlined /></template>导出需求包</a-button></a-space></div>
    <a-descriptions bordered size="small" :column="3"><a-descriptions-item label="状态"><a-tag color="cyan">{{ labels[item.derivedStatus] }}</a-tag></a-descriptions-item><a-descriptions-item label="负责人">{{ item.owner || '—' }}</a-descriptions-item><a-descriptions-item label="关联版本">{{ item.versions.length }}</a-descriptions-item></a-descriptions>
    <h3>跨项目版本演进</h3><a-table :data-source="item.versions" :columns="columns" row-key="versionNo" size="middle" :pagination="false" :scroll="{ x: 760 }"><template #bodyCell="{column,record}"><template v-if="column.key==='version'"><a @click="$router.push(`/projects/${record.project}/versions/${record.versionNo}`)">{{ record.versionNo }} · {{ record.title }}</a></template><template v-else-if="column.key==='baseline'"><a-tag :color="record.isBaseline?'green':'default'">{{ record.isBaseline?'当前基线':'非基线' }}</a-tag></template></template></a-table>
    <a-empty class="feedback-empty" description="反馈由已配置的 Issue 平台按 Flowlark 标签实时查询" />
    <a-modal v-model:open="editOpen" title="编辑需求" @ok="save" :confirm-loading="saving"><a-form layout="vertical"><a-form-item label="标题" required><a-input v-model:value="form.title" /></a-form-item><a-form-item label="描述"><a-textarea v-model:value="form.description" :rows="5" /></a-form-item><a-form-item label="负责人"><a-input v-model:value="form.owner" /></a-form-item></a-form></a-modal>
  </div>
</template>
<script setup>
import { onMounted, reactive, ref, watch } from 'vue'
import { message } from 'ant-design-vue'
import { EditOutlined, ExportOutlined } from '@ant-design/icons-vue'
import { api } from '../api'; import { useAppStore } from '../store'
const props=defineProps({code:String}),app=useAppStore(),item=ref(null),editOpen=ref(false),saving=ref(false),exporting=ref(false),form=reactive({title:'',description:'',owner:''})
const labels={not_started:'未开始',designing:'设计中',finalized:'已定稿',delivered:'已交付'}
const columns=[{title:'项目',dataIndex:'project',width:160},{title:'版本',key:'version'},{title:'基线',key:'baseline',width:120},{title:'创建时间',dataIndex:'createdAt',width:190}]
async function load(){item.value=await api.getRequirement(props.code)}
function startEdit(){Object.assign(form,{title:item.value.title,description:item.value.description,owner:item.value.owner});editOpen.value=true}
async function save(){saving.value=true;try{item.value=await api.updateRequirement(props.code,form);editOpen.value=false;message.success('需求已更新')}finally{saving.value=false}}
async function exportPackage(){exporting.value=true;try{const result=await api.exportRequirement(props.code);message.success(`已导出到 ${result.outputDir}`)}finally{exporting.value=false}}
watch(()=>props.code,load);onMounted(load)
</script>
<style scoped>
.detail-header{display:flex;align-items:flex-start;gap:16px;margin:20px 0}.detail-header>div{flex:1}.detail-header h2{margin:2px 0 6px;font-size:var(--fl-fs-5)}.detail-header p{margin:0;color:var(--fl-text-2)}.detail-page h3{margin:24px 0 12px;font-size:15px}.feedback-empty{margin-top:20px}@media(max-width:768px){.detail-header{flex-direction:column}.detail-header .ant-space{width:100%}}
</style>

// web/src/pages/RequirementDetail.tsx
import { useNavigate, useParams } from 'react-router-dom';
import { App, Button, Descriptions, Form, Input, List, Modal, Space, Tag } from 'antd';
import { EditOutlined, ExportOutlined } from '@ant-design/icons';
import { useCallback, useEffect, useState } from 'react';
import { PageHeader } from '@/components/PageHeader';
import { State } from '@/components/State';
import { useAppRuntime } from '@/runtime/AppRuntime';
import { api } from '@/services/api';
import { errorText } from '@/services/requestModel.js';
import { fmtTime, textOf } from '@/utils/format';

const statusLabels: Record<string, string> = {
  not_started: '未开始',
  designing: '设计中',
  finalized: '已定稿',
  delivered: '已交付',
};

export default function RequirementDetail() {
  const navigate = useNavigate();
  const { code = '' } = useParams();
  const { message } = App.useApp();
  const { health } = useAppRuntime();
  const writable = health?.canWrite !== false;
  const [item, setItem] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [editOpen, setEditOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [exporting, setExporting] = useState(false);
  const [form] = Form.useForm();

  const load = useCallback(async () => {
    if (!code) return;
    setLoading(true);
    setError('');
    try {
      setItem(await api.getRequirement(code));
    } catch (nextError) {
      setError(errorText(nextError, '无法读取需求详情'));
    } finally {
      setLoading(false);
    }
  }, [code]);

  const startEdit = useCallback(() => {
    form.setFieldsValue({
      title: item?.title || '',
      description: item?.description || '',
      owner: item?.owner || '',
    });
    setEditOpen(true);
  }, [form, item]);

  const save = useCallback(async () => {
    let values: any;
    try {
      values = await form.validateFields();
    } catch {
      return;
    }
    setSaving(true);
    try {
      setItem(await api.updateRequirement(code, values));
      message.success('需求已更新');
      setEditOpen(false);
    } catch (nextError) {
      message.error(errorText(nextError, '更新需求失败'));
    } finally {
      setSaving(false);
    }
  }, [code, form, message]);

  const exportPackage = useCallback(async () => {
    setExporting(true);
    try {
      const result: any = await api.exportRequirement(code);
      message.success(`已导出到 ${result.outputDir}`);
    } catch (nextError) {
      message.error(errorText(nextError, '导出需求包失败'));
    } finally {
      setExporting(false);
    }
  }, [code, message]);

  useEffect(() => {
    void load();
  }, [load]);

  return (
    <main className="fl-page">
      <PageHeader
        eyebrow="需求详情"
        title={item?.title || code}
        description={item?.description || '查看需求属性与关联原型版本。'}
        backTo="/requirements"
        actions={item ? (
          <Space wrap>
            <Button icon={<EditOutlined />} disabled={!writable} onClick={startEdit}>编辑</Button>
            <Button icon={<ExportOutlined />} loading={exporting} disabled={!writable} onClick={exportPackage}>导出需求包</Button>
          </Space>
        ) : null}
      />
      <State loading={loading} error={error} onRetry={load} empty={!item} emptyText="没有找到需求">
        <div className="fl-detail-stack">
          <section className="fl-detail-summary">
            <Descriptions column={{ xs: 1, sm: 2, lg: 3 }}>
              <Descriptions.Item label="编号"><span className="fl-mono">{code}</span></Descriptions.Item>
              <Descriptions.Item label="状态"><Tag>{statusLabels[item?.derivedStatus] || textOf(item?.derivedStatus, '未开始')}</Tag></Descriptions.Item>
              <Descriptions.Item label="负责人">{textOf(item?.owner)}</Descriptions.Item>
              <Descriptions.Item label="项目">{textOf(item?.project, '未分项目')}</Descriptions.Item>
              <Descriptions.Item label="模块">{textOf(item?.module, '未分模块')}</Descriptions.Item>
              <Descriptions.Item label="来源">{item?.external ? '需求池' : '本地'}</Descriptions.Item>
              <Descriptions.Item label="类型">{textOf(item?.type)}</Descriptions.Item>
              <Descriptions.Item label="优先级">{textOf(item?.priority)}</Descriptions.Item>
              <Descriptions.Item label="关联版本">{item?.versions?.length || 0}</Descriptions.Item>
            </Descriptions>
          </section>
          <section className="fl-detail-section">
            <h2>跨项目版本演进</h2>
            <List
              locale={{ emptyText: '还没有关联版本' }}
              dataSource={item?.versions || []}
              renderItem={(version: any) => {
                const versionNo = version.versionNo || version.no;
                return (
                  <List.Item extra={<Tag color={version.isBaseline ? 'success' : 'default'}>{version.isBaseline ? '当前基线' : '非基线'}</Tag>}>
                    <List.Item.Meta
                      title={(
                        <Button
                          type="link"
                          className="fl-result-link"
                          onClick={() => navigate(`/projects/${encodeURIComponent(version.project)}/versions/${encodeURIComponent(versionNo)}`)}
                        >
                          {version.project} / {versionNo} · {textOf(version.title)}
                        </Button>
                      )}
                      description={version.createdAt ? `创建于 ${fmtTime(version.createdAt)}` : '打开版本工作台'}
                    />
                  </List.Item>
                );
              }}
            />
          </section>
        </div>
      </State>

      <Modal title="编辑需求" open={editOpen} confirmLoading={saving} onOk={save} onCancel={() => setEditOpen(false)}>
        <Form form={form} layout="vertical">
          <Form.Item name="title" label="标题" rules={[{ required: true, message: '请填写标题' }]}><Input /></Form.Item>
          <Form.Item name="description" label="描述"><Input.TextArea rows={5} /></Form.Item>
          <Form.Item name="owner" label="负责人"><Input /></Form.Item>
        </Form>
      </Modal>
    </main>
  );
}
